### ISSUE TITLE
NFS mount Read-only file system

### ISSUE THREAD

**Issue by bokanit** [ceph/cephadm-ansible#249]
Hello 
I have new in ceph. I user branch reef to run ansible preflight and follow step from  https://docs.ceph.com/en/latest/cephadm/install/#install-cephadm .
Now kube csiand object it work but cephnfs can mount  with Read-only file system.
Have anyone cah help me.

**Comment by asm0deuz** [comment]
Sorry but this is unrelated to cephadm-ansible.
