### ISSUE TITLE
No work preflight on ubuntu jammy

### ISSUE THREAD

**Issue by itJunky** [ceph/cephadm-ansible#267]
When a run `ansible-playbook -i ../inventory.yaml cephadm-preflight.yml` getting error:
```
fatal: [UbCeph1]: FAILED! => changed=false 
  attempts: 3
  msg: 'Failed to update apt cache: W:Updating from such a repository can''t be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository ''https://download.ceph.com/debian-quincy jammy Release'' does not have a Release file.
```

After that i go to URL and see only bullseye and focal... but it is soo old!
Some search getting me repo with jammy https://download.ceph.com/debian-reef/ what is reef? How can i know about some reef?

Ok trying to use another URL by `ansible-playbook -i ../inventory.yaml cephadm-preflight.yml -e "ceph_origin=custom" -e "custom_repo_url=https://download.ceph.com/debian-reef"`

And getting same error again... WTF? You broke my apt system and doesn't get it back to working state (((
Trying to `ansible-playbook -i ../inventory.yaml cephadm-purge-cluster.yml `
And error again, but another:
```
fatal: [UbCeph1 -> localhost]: FAILED! => changed=false 
  msg: |-
    You must provide the cluster fsid to be purged.
    e.g. ansible-playbook -i <inventory host file> cephadm-purge-cluster.yml -e fsid=<your fsid>
```
Aaaaammm... What is fsid? Where i can get it? Nothing info about it...
Okay, going to remove broken repos on servers manually by hands FU#$%$#$%#$%....

Try again `ansible-playbook -i ../inventory.yaml cephadm-preflight.yml -e "ceph_origin=custom" -e "custom_repo_url=https://download.ceph.com/debian-reef"`

And error again FU#$%$#$%#$%....
```
fatal: [UbCeph1]: FAILED! => 
  msg: '''ceph_custom_repositories'' is undefined. ''ceph_custom_repositories'' is undefined'
```

It is totally unusable for fresh ubuntu distros (((
How can i use it correctly with my env?

What value needed for ceph_custom_repositories ?

**Comment by itJunky** [comment]
I found some more but this confused me even more:

```
custom_repo_url
~~~~~~~~~~~~~~~
**description**
  The url of the repository when ``ceph_origin`` is 'custom'.
  Mutually exclusive with ``ceph_custom_repositories``.
```
But:

```
msg: "You must define 'ceph_custom_repositories' or 'custom_repo_url' when ceph_origin is 'custom'"
```

How it can be if `Mutually exclusive with ``ceph_custom_repositories```?

**Comment by asm0deuz** [comment]
I think you should start by reading the Ceph documentation [https://docs.ceph.com/en/reef/](url) to understand the concepts then feel free to contribute to the project to improve it.
