### ISSUE TITLE
Remove the client role from the preflight playbook, now that we have a dedicated client playbook?

### ISSUE THREAD

**Issue by sebastian-philipp** [ceph/cephadm-ansible#27]
To avoid confusion? Can we do that?

**Comment by VasishtaShastry** [comment]
@sebastian-philipp As of now the new client playbook is just installing ceph-common
where as preflight can be used to update
@pcuzner

**Comment by guits** [comment]
> To avoid confusion? Can we do that?


@sebastian-philipp I think we can (I would even say we should) rework those 2 playbooks, yes.

I'm working on a patch for this
