### ISSUE TITLE
preflight should provide the option of deploying multipathing

### ISSUE THREAD

**Issue by pcuzner** [ceph/cephadm-ansible#64]
If the osd host is using an external enclosure, the SAS devices could be multipathed. In this scenario multipathing is needed to avoid data corruption. 

Perhaps during preflight there could be a variable that the admin can set that will include a multipathing role during the preparation of the host?

**Comment by asm0deuz** [comment]
@pcuzner Do you mean dealing with DM Multipath? Usually it is already configured at OS deployment step but could you elaborate what the variable would help to do.

Thx
