### ISSUE TITLE
run CI tests on el9

### ISSUE THREAD

**Issue by ktdreyer** [ceph/cephadm-ansible#67]
Currently users run `cephadm-ansible` on RHEL 8. We need to be able to run `cephadm-ansible` on RHEL 9 too.

RHEL 9 ships its own (minimal) version of `ansible-core` so we need to make sure `cephadm-ansible` works with that Ansible version.

Can you please add CI tests to run on RHEL 9?

**Comment by guits** [comment]
I'm unsure if it makes sense to run against RHEL 9 in upstream CI.
Can't we use CentOS stream 9 instead?

**Comment by ktdreyer** [comment]
Sure, CentOS Stream 9 is fine for upstream.

**Comment by guits** [comment]
ok, added this in my todo list 🙂
