### ISSUE TITLE
Is Ansible 2.10 actually required?

### ISSUE THREAD

**Issue by tserlin** [ceph/cephadm-ansible#9]
We're looking at packaging cephadm-ansible downstream, and the requirement in "cephadm-ansible.spec.in" is for Ansible 2.10.

However, Ansible 2.9.22 is the latest version available in RHEL 8 and RHEL 7. I don't even see Ansible 2.10 in the just-released Fedora 34.

Is cephadm-ansible dependent on something in Ansible 2.10 that's not in Ansible 2.9?

Thanks.

**Comment by guits** [comment]
> Is cephadm-ansible dependent on something in Ansible 2.10 that's not in Ansible 2.9?

I don't think 2.10 is a requirement here, we should be able to use 2.9, I'll double-check this and let you know asap

**Comment by guits** [comment]
@tserlin see https://github.com/ceph/cephadm-ansible/pull/8/commits/3f5d3c731c17d079f035ab82392a51b248b1fafe

2.9 is ok

**Comment by zdover23** [comment]
Is there an obvious place that this has docs impact?

Zac Dover
Upstream Docs
Ceph
